[build]
target = "thumbv4t-none-eabi"
[unstable]
build-std = ["core", "alloc"]

[target.thumbv4t-none-eabi]
rustflags = ["-Clink-arg=-Tarm7_link.ld", "-Ctarget-cpu=arm7tdmi"]

[target.armv4t-none-eabi]
rustflags = ["-Clink-arg=-Tarm7_link.ld", "-Ctarget-cpu=arm7tdmi"]
