[build]
target = "thumbv5te-none-eabi"
[unstable]
build-std = ["core", "alloc"]

[target.thumbv5te-none-eabi]
rustflags = ["-Clink-arg=-Tarm9_link.ld", "-Ctarget-cpu=arm946e-s"]
# Can try using this if lld is acting up.
#linker = "arm-none-eabi-ld"

[target.armv5te-none-eabi]
rustflags = ["-Clink-arg=-Tarm9_link.ld", "-Ctarget-cpu=arm946e-s"]
