[build]
target = "thumbv5te-none-eabi.json"
[unstable]
build-std = ["core", "alloc"]

[target.thumbv5te-none-eabi]
#linker = "arm-none-eabi-ld"
rustflags = ["-Clink-arg=-Tarm9_link.ld", "-Ctarget-cpu=arm946e-s"]

[target.armv5te-none-eabi]
rustflags = ["-Clink-arg=-Tarm9_link.ld", "-Ctarget-cpu=arm946e-s"]
